### ISSUE TITLE
Indenting if

### ISSUE THREAD

**Issue by hanshuebner** [xquery-mode/cider-any#12]
If I enter this:

```
if ($facility-type = "GROUP") then

```

and then press TAB on the empty line (with auto-indent enabled), I would expect an indent of 2 characters, but the cursor stays flush left.

I'll write separate indentation issues for everything that I find.

**Comment by proofit404** [comment]
Can I ask you to report indentation issues in the xquery-mode bug tracker. It will be easier to manage them this way.
