### ISSUE TITLE
Make XQuery result buffer read only & focused

### ISSUE THREAD

**Issue by hanshuebner** [xquery-mode/cider-any#5]
The XQuery result buffer should be read-only, focused after evaluation and be buried when "q" is pressed.

**Comment by hanshuebner** [comment]
This works, but when "q" is typed to close the buffer, the XQuery buffer should be focused again.  Currently, the buffer under the XQuery result buffer gets the focus.

**Comment by hanshuebner** [comment]
Also, when the window is split to display the XQuery result buffer, it should be unsplit again when "q" is typed.

**Comment by proofit404** [comment]
Ok, I will fix this tonight.

**Comment by proofit404** [comment]
I think `quit-window` should work for you.

**Comment by hanshuebner** [comment]
Works great!  Thanks!
