### ISSUE TITLE
Don't makr backend as initialized until init-handler applies successfully.

### ISSUE THREAD

**Issue by proofit404** [xquery-mode/cider-any#6]

**Comment by hanshuebner** [comment]
This is actually bugging me a lot, as I need to restart emacs when I forget to start the repl first.  Is there a workaround?

**Comment by proofit404** [comment]
Will fix tonight. I was digging solutions for @m-g-r suggestions. For now `M-: (setq cider-any-initiated-backends nil) RET` should work for you.

**Comment by proofit404** [comment]
Fixed. I removed initialization step completely, so no tricky asynchronous connection state handling is necessary.
