### ISSUE TITLE
support empty results

### ISSUE THREAD

**Issue by m-g-r** [xquery-mode/cider-any#7]
Hi, cool thing! I noticed that it is not supported that an xquery might have an empty result (which is perfectly ok, if you do something like xdmp:document-load in MarkLogic).

In cider-any-uruk I get:
error in process filter: Wrong type argument: char-or-string-p, nil

Bye Max

**Comment by m-g-r** [comment]
Trivial test case:
for $foo in () return $foo

**Comment by proofit404** [comment]
Thanks! Will fix ASAP.

**Comment by m-g-r** [comment]
Thanks, Artem! That'd be great.

**Comment by proofit404** [comment]
Fixed in the `callback-chain` branch.

**Comment by m-g-r** [comment]
Cool, I cherry-picked it and it works nicely.

I suggest to rephrase the message "Evaluation completes with on result". You mean "without", right?
ML says: "your query returned an empty sequence". I think something like that is more correct. An empty result is also a result.

**Comment by proofit404** [comment]
I've fix this report message according to your recommendations.

**Comment by m-g-r** [comment]
Thank you.

**Comment by proofit404** [comment]
Merged into master.
